name: "Build release APKs"
on:
  pull_request:
    branches:
      - main
      - master

  push:
    branches:
      - main
      - master
      - develop

jobs:
  build:
    name: Build release APKs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      
      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.2'
      
      - name: Decode android/app/upload-keystore.jks
        run: echo "${{ secrets.KEYSTORE_JKS_PROD }}" | base64 --decode > android/app/upload-keystore.jks

      - name: Decode android/key.properties
        run: echo "${{ secrets.KEY_PROPERTIES_PROD }}" | base64 --decode > android/key.properties

      - run: flutter pub get
      - run: flutter test
      - name: Build Apk
        run: flutter build apk --split-per-abi --build-number=${GITHUB_RUN_NUMBER}

      # - name: Sign APK
      #   uses: r0adkll/sign-android-release@v1
      #   with:
      #     releaseDirectory: build/app/outputs/flutter-apk
      #     signingKeyBase64: ${{ secrets.SIGNING_KEY }}
      #     alias: ${{ secrets.ALIAS }}
      #     keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
      #     keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Get SHA-256 Checksums
        run: |
          set -e
          mv build/app/outputs/flutter-apk/app.apk app.apk
          sha=`sha256sum app.apk | awk '{ print $1 }'`
          echo "APK_UNIVERSAL_SHA=$sha" >> $GITHUB_ENV

          cp build/app/outputs/flutter-apk/app-arm64-v8a-release.apk app-arm64-v8a-release.apk
          sha=`sha256sum app-arm64-v8a-release.apk | awk '{ print $1 }'`
          echo "APK_ARM64_V8A_SHA=$sha" >> $GITHUB_ENV

          cp build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk app-armeabi-v7a-release.apk
          sha=`sha256sum app-armeabi-v7a-release.apk | awk '{ print $1 }'`
          echo "APK_ARMEABI_V7A_SHA=$sha" >> $GITHUB_ENV

          cp build/app/outputs/flutter-apk/app-x86_64-release.apk app-x86_64-release.apk
          sha=`sha256sum app-x86_64-release.apk | awk '{ print $1 }'`
          echo "APK_X86_SHA=$sha" >> $GITHUB_ENV

      # - name: Get apk path
      #   id: apk-path
      #   run: |
      #     path=$(find **/build/outputs/apk -name '*.apk' -type f | head -1)
      #     echo "::set-output name=path::$path"

      - name: Get Apk Info
        id: apk-info
        uses: hkusu/apk-info-action@v1
        with:
          apk-path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk

      - name: Show Apk Info
        run: echo "APK_VERSION=${{ steps.apk-info.outputs.version-name }}" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.APK_VERSION }}-${{ github.run_number }}
          name: Extra v${{ env.APK_VERSION }}-${{ github.run_number }}
          body: |
            ---
            ### Checksums
            | Variant | SHA-256 |
            | ------- | ------- |
            | arm64-v8a | ${{ env.APK_ARM64_V8A_SHA }}
            | armeabi-v7a | ${{ env.APK_ARMEABI_V7A_SHA }}
            | x86 | ${{ env.APK_X86_SHA }} |
          files: |
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            build/app/outputs/flutter-apk/app-x86_64-release.apk
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Commit on Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            Extra v${{ env.APK_VERSION }}-${{ github.run_number }}
            ---------------
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See previous releases: https://github.com/${{ github.repository }}/releases
          document: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
          document: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
          document: build/app/outputs/flutter-apk/app-x86_64-release.apk

      # - name: Sign APK
      #   uses: r0adkll/sign-android-release@v1
      #   with:
      #     releaseDirectory: build/app/outputs/apk/release
      #     signingKeyBase64: ${{ secrets.SIGNING_KEY }}
      #     alias: ${{ secrets.ALIAS }}
      #     keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
      #     keyPassword: ${{ secrets.KEY_PASSWORD }}

      # - uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "build/app/outputs/apk/release/*"
      #     tag: v1.0.${{ github.run_number }}
      #     token: ${{ secrets.TOKEN }}